### ISSUE TITLE
[CK legacy -> CK2] Replacing Versions with Variations

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/ck#142]
In CK package release versions can be handled by variations as done in the below package for opencv. I believe the same can be used to replace versions in CK. The only missing thing will be the prompt to choose from the available versions. For this can we add an option to show all possible variations when user adds a flag like say "--show" (show variations)?  The list of variations could be pretty long and so we can add a special flag for certain variations - say "master variation" which can be used for released versions or something even broader (say gpu/cpu variants)  and only those can be shown under "--show". I hope this can increase the user-friendliness of CK.

https://github.com/ctuning/ck-math/blob/master/package/lib-opencv/.cm/meta.json

**Comment by gfursin** [comment]
Hi @arjunsuresh. 

Thank you for your message! Indeed, we can use variations to substitute multiple CK entries for different packages. However, it brings backwards incompatibility. 

When program workflows in CK resolve dependencies, CK searchers for packages with different versions and asks a user to select a given package with a given version. This is the default behavior. Furthermore, I introduced a flag "--quiet" long time ago to select the default version, i.e.
```
ck run program:xyz --quiet
```

When we have all versions represented as variations in one package, this default behavior breaks and CK selects the default version rather than asking a user about the selection. 

That is why, to restore the original behavior that it backwards compatible, I now ask user to select a version from variations by default. And, just like before, you can force CK to select default versions by using the flag --quiet.

That's why I think that we do not need to do any further changes since you can use the --quiet flag ...

I started updating Docker images and travis to restore this default behavior (see example in our main [ck-ml repo](https://github.com/ctuning/ck-ml/blob/main/.travis.yml#L83). You can probably do the same in your forked repositories ...

However, I am happy to discuss it further if you have other ideas. Thank you very much again for supporting this community project!

**Comment by arjunsuresh** [comment]
Thank you @gfursin for your valuable reply. I now understand that we can have the old default variation working if we pass the "--quiet" flag. Does this also imply that we can avoid replicating the repo code to maintain different versions -- I feel this is absolutely necessary to make CK repositories easily manageable.

**Comment by gfursin** [comment]
You are welcome, @arjunsuresh!

We discovered [some minor issues](https://github.com/ctuning/ck/issues/142) with using versions in variations when replaying experiments. Nevertheless, we plan to convert some old packages with versions in their names into packages with variations to compact them this summer (we plan to redesign the env/soft/package mechanism in CK v3 anyway).

If you plan to update some packages, please tell us to avoid duplicate work. Feel free to submit them to our main repository with all aggregated components: https://github.com/ctuning/ai . Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin, 

Is there a kernel setting where we can turn on `--quiet` automatically for all `ck install` commands? This would make most/all of our repos compatible with latest CK version as opposed to 1.55.5.  Thank you!

**Comment by gfursin** [comment]
Hi @arjunsuresh .
Sorry for my radio silence - I was offline for some time due to family issues.
There is no kernel setting to turn on --quiet mode but it should be relatively easy to add. I am in favor!
Do you think you can add this kernel setting (maybe in sync with @ens-lg4) and provide a PR?
Thanks a lot and have a good weekend!

**Comment by arjunsuresh** [comment]
Thank you @gfursin for your reply. I have added this now. Have a nice weekend :) 

https://github.com/mlcommons/ck/pull/180/commits/cdecf6cd418dc1d6a340c135bf91b45cfc5491c1

**Comment by gfursin** [comment]
Let's discuss it during the CK2 framework development.

**Comment by arjunsuresh** [comment]
We now support both `variations` and `versions` in a clean way in CK2/CM.
