### ISSUE TITLE
[CK legacy] MLperf-automation on the Pi 4, Object Detection example

### ISSUE THREAD

**Issue by ghost** [mlcommons/ck#182]
I followed the instructions https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation/reproduce/ck-object-detection-rpi4-tflite.md for Raspian OS Pi 4 and I came across these errors.

One was when installing `ck install package --tags=lib,mlperf,loadgen,static` it produced an error on the logging.h file. What I did was the delete the lines 713-732 (for loop).

Next, when running the [performance benchmark](https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation/reproduce/ck-object-detection-rpi4-tflite.md#performance) it fails to create the Accuracy.json and doesn't catch the error. It works fine though outputting the latencies until that point.

Moreover, the GCC 8.x version worked fine for me.

**Comment by gfursin** [comment]
Thank you for your report @ghost! 

I am afraid your issue is still related to using GCC 8.x.
I remember that I struggled a lot trying to make MLPerf work with GCC 8 on RPi4 and failed. 
Eventually, it worked with GCC 9+ after some magic. 

Can you please try to run above commands with GCC 9+, please? If it will fail with GCC 9+, then maybe there is a new issue that we need to investigate ...

Thanks!

**Comment by gfursin** [comment]
By the way, please, don't forget to provide all related logs with your issues. Thanks!!!

**Comment by gfursin** [comment]
We will continue reproducing MLPerf results in the [reproducibility project](https://github.com/mlcommons/ck/blob/master/docs/mlperf-automation-cm/reproducibility.md).
