### ISSUE TITLE
[MLPerf] C++ implementation with RetinaNet + ONNX + CPU doesn't produce summary.json

### ISSUE THREAD

**Issue by gfursin** [mlcommons/ck#501]
Hi @arjunsuresh . I tried this command:
```
cm pull repo mlcommons@ck

cm run script "get sys-utils-cm" --quiet

cm run script "install python-venv" --version=3.10.7 --name=mlperf

cm run script --tags=run,mlperf,inference,generate-run-cmds,_submission,_short,_dashboard \
      --adr.python.extra_cache_tags=venv-mlperf \
      --adr.python.version_min=3.8 \
      --adr.compiler.tags=gcc \
      --adr.openimages-preprocessed.tags=_500 \
      --submitter="OctoML" \
      --hw_name=default \
      --lang=cpp \
      --model=retinanet \
      --backend=onnxruntime \
      --device=cpu \
      --scenario=Offline \
      --test_query_count=10 \
      --rerun
```

And it seems to be working but in the end the summary.csv is empty ... Do you know what may have happened?

[cpp.log](https://github.com/mlcommons/ck/files/9997953/cpp.log)

I attached the log. Thanks!

**Comment by arjunsuresh** [comment]
Hi @gfursin, this is due to submission checker failing when large files (>50MB) are present. Our CPP implementation is having a large trace file which is empty for the python one. [This](https://github.com/octoml/ck/commit/eef8e0bf445d950ab94d761dade19a2d421541a9) commit removes this file from the submission tree and so should fix this issue.

**Comment by gfursin** [comment]
It works now! Thanks!!!
